<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/PureEngine.Player/PureEngine.Player.csproj" />
    <PackageReference Include="Avalonia.Headless" Version="12.1.2" />
  </ItemGroup>
</Project>
