using System.Reflection;
using System.Runtime.Versioning;
using System.Xml.Linq;
using Microsoft.Extensions.DependencyInjection;
using PureEngine.Analyzers;
using PureEngine.Core;

namespace PureEngine.Editor;

/// <summary>Standard MSBuild metadata for external C# editors, including Zed/Roslyn.</summary>
public static class ProjectCodeWorkspace
{
    private const string GeneratedMarker = "Generated by PureEngine for C# editing.";
    public const string ProjectName = "PureEngine.Game.csproj";

    public static void Ensure(ProjectFile project)
    {
        var path = Path.Combine(project.RootDirectory, ProjectName);
        var exists = File.Exists(path);
        // A hand-maintained project takes precedence over generated editor metadata.
        if (exists && !File.ReadAllText(path).Contains(GeneratedMarker, StringComparison.Ordinal)) return;
        if (!exists && Directory.EnumerateFiles(project.RootDirectory, "*.csproj").Any()) return;

        var core = typeof(Scene).Assembly;
        var framework = new FrameworkName(core.GetCustomAttribute<TargetFrameworkAttribute>()!.FrameworkName);
        var document = new XDocument(new XComment(GeneratedMarker),
            new XElement("Project", new XAttribute("Sdk", "Microsoft.NET.Sdk"),
                new XElement("PropertyGroup",
                    new XElement("TargetFramework", $"net{framework.Version.Major}.{framework.Version.Minor}"),
                    // Match the embedded Roslyn compiler rather than the installed SDK's defaults.
                    new XElement("LangVersion", "13.0"),
                    new XElement("ImplicitUsings", "disable"),
                    new XElement("Nullable", "disable"),
                    new XElement("CheckForOverflowUnderflow", "true"),
                    new XElement("DefaultItemExcludes", "$(DefaultItemExcludes);**/bin/**;**/obj/**;**/.*/**")),
                new XElement("ItemGroup",
                    new XElement("Analyzer", new XAttribute("Include", typeof(LifecycleUsageSuppressor).Assembly.Location)),
                    new XElement("Reference", new XAttribute("Include", "PureEngine.Core"),
                        new XElement("HintPath", core.Location),
                        new XElement("Private", "false")))));
        foreach (var assembly in new[] { typeof(IServiceCollection).Assembly, typeof(ServiceProvider).Assembly })
            document.Root!.Element("ItemGroup")!.Add(
                new XElement("Reference", new XAttribute("Include", assembly.GetName().Name!),
                    new XElement("HintPath", assembly.Location), new XElement("Private", "false")));
        var content = document.ToString() + Environment.NewLine;
        if (!exists || File.ReadAllText(path) != content) SceneFile.Write(path, content);

        // Give Roslyn an unambiguous solution entry point; preserve existing solutions.
        if (!Directory.EnumerateFiles(project.RootDirectory, "*.sln").Any()
            && !Directory.EnumerateFiles(project.RootDirectory, "*.slnx").Any())
        {
            var solution = new XElement("Solution",
                new XElement("Project", new XAttribute("Path", ProjectName)));
            SceneFile.Write(Path.Combine(project.RootDirectory, "PureEngine.Game.slnx"), solution.ToString());
        }

        var sdkPath = Path.Combine(project.RootDirectory, "global.json");
        if (!File.Exists(sdkPath))
        {
            using var sdk = typeof(ProjectCodeWorkspace).Assembly.GetManifestResourceStream("PureEngine.Sdk.json")!;
            using var reader = new StreamReader(sdk);
            SceneFile.Write(sdkPath, reader.ReadToEnd());
        }
    }
}
