<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net11.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PureEngine.Rendering/PureEngine.Rendering.csproj" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
  </ItemGroup>
</Project>
