<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PureEngine.Core/PureEngine.Core.csproj" />
    <Compile Include="../PureEngine.Editor/ComponentAssets.cs" Link="ComponentAssets.cs" />
    <Compile Include="../PureEngine.Editor/Samples/*.cs" Link="Samples/%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
